ar_layers: []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: []
  ar_reg: null
  n_lags: 64
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: &id002 !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 163123200000000000
        - 10
        shift: &id003 !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1533254400000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id001 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          nnA9ClcDrEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          ZmZmZma2VEA=
    - - high
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          bj0K1yNVrUA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          MzMzMzMTVUA=
    - - volume
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          mJmZYTKgukE=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          AAAAAJC5B0E=
    - - foreignNotional
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          c6gAuzRzx0E=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          RGB5SD5eX0E=
    - - low
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          ULgehev/qkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          ZmZmZmYmVEA=
    - - open
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          nnA9ClcDrEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id001
        - !!binary |
          ZmZmZma2VEA=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: *id002
              shift: *id003
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                nnA9ClcDrEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                ZmZmZma2VEA=
          - - high
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                bj0K1yNVrUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                MzMzMzMTVUA=
          - - volume
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                mJmZYTKgukE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                AAAAAJC5B0E=
          - - foreignNotional
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                c6gAuzRzx0E=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                RGB5SD5eX0E=
          - - low
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                ULgehev/qkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                ZmZmZmYmVEA=
          - - open
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                nnA9ClcDrEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id001
              - !!binary |
                ZmZmZma2VEA=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object/apply:collections.OrderedDict
- - - high
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
  - - volume
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
  - - foreignNotional
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
  - - low
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
  - - open
    - !!python/object:neuralprophet.configure.Regressor
      mode: additive
      normalize: auto
      reg_lambda: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 365.25
        resolution: 6
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        period: 7
        resolution: 3
  reg_lambda: 0
  weekly_arg: true
  yearly_arg: true
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 162
  lambda_delay: 81
  learning_rate: 0.003
  loss_func: !!python/object:neuralprophet.custom_loss_metrics.PinballLoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: !!python/object/apply:collections.OrderedDict
    - - - loss_func
        - !!python/object:torch.nn.modules.loss.SmoothL1Loss
          _backward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _buffers: !!python/object/apply:collections.OrderedDict
          - []
          _forward_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _is_full_backward_hook: null
          _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
          - []
          _modules: !!python/object/apply:collections.OrderedDict
          - []
          _non_persistent_buffers_set: !!set {}
          _parameters: !!python/object/apply:collections.OrderedDict
          - []
          _state_dict_hooks: !!python/object/apply:collections.OrderedDict
          - []
          beta: 1.0
          reduction: none
          training: true
    _non_persistent_buffers_set: !!set {}
    _parameters: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    quantiles:
    - 0.5
    - 0.2
    - 0.8
    reduction: mean
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 1825
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  - 0.2
  - 0.8
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 5000.0
    pct_start: 0.3
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 10
  trend_global_local: global
  trend_reg: 0
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: []
max_lags: 64
meta_used_in_model: false
metrics:
  MAE: !!python/object/new:torchmetrics.regression.mae.MeanAbsoluteError
    args:
    - MeanAbsoluteError()
    state:
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: !!python/object/apply:collections.OrderedDict
      - []
      _cache: null
      _computed: null
      _defaults:
        sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
            Z2UKcQFYCgAAADIxNjAwOTMwMjRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyMTYwMDkz
            MDI0cQFhLgEAAAAAAAAAAAAAAA==
        - 0
        - !!python/tuple []
        - !!python/tuple []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
        total: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
            ZQpxAVgKAAAAMjE2MDA5Mzc5MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADIxNjAwOTM3
            OTJxAWEuAQAAAAAAAAAAAAAAAAAAAA==
        - 0
        - !!python/tuple []
        - !!python/tuple []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
      _device: !!python/object/apply:torch.device
      - cpu
      _dtype_convert: false
      _enable_grad: false
      _forward_cache: null
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _is_synced: false
      _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: !!python/object/apply:collections.OrderedDict
      - []
      _non_persistent_buffers_set: !!set {}
      _parameters: !!python/object/apply:collections.OrderedDict
      - []
      _persistent:
        sum_abs_error: false
        total: false
      _reductions:
        sum_abs_error: &id004 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
        total: *id004
      _should_unsync: true
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _to_sync: true
      _update_count: 0
      compute_on_cpu: false
      dist_sync_fn: null
      dist_sync_on_step: false
      distributed_available_fn: &id005 !!python/name:torchmetrics.metric.jit_distributed_available ''
      process_group: null
      sum_abs_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADIxNjAwOTM0MDhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyMTYwMDkz
          NDA4cQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      sync_on_compute: true
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgKAAAAMjE2MDA5NTA0MHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADIxNjAwOTUw
          NDBxAWEuAQAAAAAAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      training: true
  RMSE: !!python/object/new:torchmetrics.regression.mse.MeanSquaredError
    args:
    - MeanSquaredError()
    state:
      _backward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _buffers: !!python/object/apply:collections.OrderedDict
      - []
      _cache: null
      _computed: null
      _defaults:
        sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
            Z2UKcQFYCgAAADIxNjAwOTUxMzZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyMTYwMDk1
            MTM2cQFhLgEAAAAAAAAAAAAAAA==
        - 0
        - !!python/tuple []
        - !!python/tuple []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
        total: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
            ZQpxAVgKAAAAMjE2MDA5NDA4MHECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADIxNjAwOTQw
            ODBxAWEuAQAAAAAAAAAAAAAAAAAAAA==
        - 0
        - !!python/tuple []
        - !!python/tuple []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
      _device: !!python/object/apply:torch.device
      - cpu
      _dtype_convert: false
      _enable_grad: false
      _forward_cache: null
      _forward_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _is_full_backward_hook: null
      _is_synced: false
      _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _modules: !!python/object/apply:collections.OrderedDict
      - []
      _non_persistent_buffers_set: !!set {}
      _parameters: !!python/object/apply:collections.OrderedDict
      - []
      _persistent:
        sum_squared_error: false
        total: false
      _reductions:
        sum_squared_error: *id004
        total: *id004
      _should_unsync: true
      _state_dict_hooks: !!python/object/apply:collections.OrderedDict
      - []
      _to_sync: true
      _update_count: 0
      compute_on_cpu: false
      dist_sync_fn: null
      dist_sync_on_step: false
      distributed_available_fn: *id005
      process_group: null
      squared: false
      sum_squared_error: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYCgAAADIxNjAwOTQ3NTJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAyMTYwMDk0
          NzUycQFhLgEAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      sync_on_compute: true
      total: !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
          ZQpxAVgKAAAAMjE2MDA4OTQ3MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYCgAAADIxNjAwODk0
          NzJxAWEuAQAAAAAAAAAAAAAAAAAAAA==
      - 0
      - !!python/tuple []
      - !!python/tuple []
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
      training: true
n_forecasts: 1
n_lags: 64
num_seasonalities_modelled: 1
num_trends_modelled: 1
